language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  firefox: latest-esr
install:
  - pip install flake8
  - pip install "selenium<3"
  - pip install .
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - flake8
  - nosetests -v tests
deploy:
  provider: pypi
  user: wg_webqaa
  password:
    secure: "PWaowyka8yJR8lBjCcGyQxiZG9k46puVMtZ2RFhciH1SwJaSYbxDjkuT0eJPNOkiaB9RYr1+Fe+XhJ1MjB1hMsOJYmFLXkM4uxrehDfpUc16qK3tcE4ke/33sZvOmPj9fULKmwkDgE1HtSGEc9zHjA6I3TeJfoFzNf9W+hvFJDs="
  on:
    tags: true
    distributions: sdist
    repo: wgnet/webium
